composant alerte - premiers pas
betagouv/dsfr-view-components pull request #95
Opened 2022-10-26 10:12 UTC by adipasquale

cf #58

2022-10-26 10:20 UTC, freesteph commented
Ça te dérange de garder les commits en anglais ?

Genre un commit message très simple

```
components: alert

Fixes #58 
```

Et avec le contenu du message ça close l'issue dès que c'est merge.

2022-11-22 10:54 UTC, freesteph requested changes

2022-11-22 10:54 UTC, freesteph commented on guide/lib/examples/alert_helpers.rb
> +          | Merci de vous être inscrit·e
> Merci de votre inscription

2022-11-22 10:54 UTC, freesteph commented on guide/lib/examples/alert_helpers.rb
> +        = dsfr_alert(type: :error, size: :sm, title: "Erreur db 123")
pas de contenu ? Et `erreur db 123` c'est pas très réaliste je trouve 

> Une erreur est survenue pendant votre inscription, veuillez contacter votre administrateur.

2022-11-22 10:54 UTC, freesteph commented on guide/lib/examples/alert_helpers.rb
> +          | Belle partie !
On peut rester sur le thème de l'inscription pour plus de cohérence ?

> Votre inscription a bien été enregistrée

2022-11-22 10:54 UTC, freesteph commented on spec/components/dsfr_component/alert_component_spec.rb
> +        "La base de données est en carafe"
😄

2022-11-22 10:54 UTC, freesteph commented on spec/components/dsfr_component/alert_component_spec.rb
> +  context "when type error without content" do
pas compris

2022-11-22 10:54 UTC, freesteph commented on spec/components/dsfr_component/alert_component_spec.rb
> +  context "when type success without content with size sm" do
pas compris

2022-11-22 10:54 UTC, freesteph commented on spec/components/dsfr_component/alert_component_spec.rb
> +  context "when type error without content" do
ah si OK

tu peux sudiviser comme ça plutôt ? 

```
context 'of type error'
  context 'without content'
    it 'xyz'

context 'of type success'

# etc
```

2022-11-22 12:23 UTC, adipasquale commented on app/components/dsfr_component/alert_component.rb
> +  def initialize(type:, title: nil, size: :md, close_button: false, classes: [], html_attributes: {})
j'ai un peu mélangé car la doc est pas super claire.

à la fois le titre et le content sont optionnels sur la version SM (il faut l'un des deux). 

ici le défaut est correct mais je vais modifier en dessous

2022-11-22 12:23 UTC, adipasquale commented on app/components/dsfr_component/alert_component.rb
> +    type.present? && type.in?(TYPES)
exact 👍 je vais corriger

2022-11-22 12:23 UTC, adipasquale commented on guide/lib/examples/alert_helpers.rb
> +          | Belle partie !
okay comme tu veux moi je me lache un peu sur les exemples pour m'amuser mais si tu veux on fait sérieux sérieux

2022-11-22 12:23 UTC, adipasquale commented on guide/lib/examples/alert_helpers.rb
> +          | Merci de vous être inscrit·e
alleeez viens on pousse l'écriture inclusive :trollface:

2022-11-22 12:23 UTC, adipasquale commented on spec/components/dsfr_component/alert_component_spec.rb
> +  context "when type error without content" do
perso je préfère limiter au maximum le nombre de niveaux pour que chaque exemple soit lisible sans avoir besoin de remonter plein de niveaux, d'aller voir des définitions de variables et de contextes à des niveaux supérieurs.

c'est ce que j'essayais d'expliquer dans ma description PR.

je vais pas forcément me battre sur ce point mais d'expérience je préfère largement écrire les tests avec beaucoup de redondance et peu d'imbrication pour réussir à les relire et les corriger quand ils plantent dans le futur

2022-11-22 12:51 UTC, freesteph commented on guide/lib/examples/alert_helpers.rb
> +          | Merci de vous être inscrit·e
https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/jameliore-le-design-et-lexperience-utilisateur/boite-a-outils/ecriture-inclusive

2022-11-22 12:51 UTC, freesteph commented on guide/lib/examples/alert_helpers.rb
> +          | Merci de vous être inscrit·e
je préfère qu'on fasse de la voix passive

2022-11-22 13:50 UTC, adipasquale commented on guide/lib/examples/alert_helpers.rb
> +          | Merci de vous être inscrit·e
okidoki j'aurais essayé

2022-11-22 14:13 UTC, freesteph commented on spec/components/dsfr_component/alert_component_spec.rb
> +  context "when type error without content" do
OK écrivons nos tests comme on les entends et on pourra converger plus tard

2022-12-01 14:10 UTC, merged